[package]
name = "zoneminder-shared-sys"
version = "0.1.0"
authors = ["hab <_@habnab.it>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
dotenv = "0.15.0"
mozjpeg = "0.8.22"
mysql = "20.1.0"
nix = "0.19.1"
